In [1]:
import spacy

In [2]:
from spacy import displacy

In [3]:
text = "Programming languages: Python, R, C++, Javascript."

In [4]:
nlp = spacy.load("en_core_web_sm")

In [5]:
doc = nlp(text)

In [6]:
displacy.render(doc, style="ent")

In [7]:
nlp.pipeline

[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x17f20e080>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x17f20dc00>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x17f1184a0>),
 ('attribute_ruler',
  <spacy.pipeline.attributeruler.AttributeRuler at 0x17f0482c0>),
 ('lemmatizer', <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x17f396300>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x17f1186d0>)]

In [23]:
nlp.remove_pipe('ner')

ValueError: [E001] No component 'ner' found in pipeline. Available names: ['tok2vec', 'tagger', 'parser', 'senter', 'attribute_ruler', 'lemmatizer']

In [25]:
nlp.pipeline

[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x13069e200>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x13069e0e0>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x1306b93f0>),
 ('attribute_ruler',
  <spacy.pipeline.attributeruler.AttributeRuler at 0x1312c9780>),
 ('lemmatizer', <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x127db6700>)]

In [27]:
displacy.render(nlp(text), style="ent")

In [31]:
TRAIN_DATA = [
                ("Python, Ruby, Javascript", {"entities": [(0, 6, "PROGLANG"), (8,4, "PROGLANG"), (14,10)]}),
                ("Proficient in Python", {"entities": [(14,6, "PROGLANG")]})
            ]

In [33]:
TRAIN_DATA

[('Python, Ruby, Javascript',
  {'entities': [(0, 6, 'PROGLANG'), (8, 4, 'PROGLANG'), (14, 10)]}),
 ('Proficient in Python', {'entities': [(14, 6, 'PROGLANG')]})]

In [34]:
!pip3 install pandas

Collecting pandas
  Using cached pandas-1.5.2-cp310-cp310-macosx_11_0_arm64.whl (10.8 MB)
Requirement already satisfied: numpy>=1.21.0 in ./jupyternev/lib/python3.10/site-packages (from pandas) (1.24.1)
Collecting pytz>=2020.1
  Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.4/499.4 kB 1.6 MB/s eta 0:00:00[31m1.1 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.1 in ./jupyternev/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in ./jupyternev/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: pytz, pandas
Successfully installed pandas-1.5.2 pytz-2022.7.1

In [35]:
import pandas as pd

In [36]:
COMPANIES = "./data/companies/companies.csv"

In [38]:
df = pd.read_csv(COMPANIES)

In [39]:
df.head()

,NAME,CATEGORY,INDUSTRY TYPE,LOCATIONS,TAGS,FOUNDED,SIZE,ABOUT,LOGO URL,WEBSITE,HEADQUARTERS
0,Haier Appliances,MNCs,Private,"Pune(Ranjangaon) Greater Noida, Delhi / NCR Pune",Consumer Electronics & AppliancesElectronicsMa...,2004 (19 yrs old),1001-5000,"""Haier India is a 100 percent subsidiary of Ha...",https://img.naukimg.com/logo_images/groups/v1/...,NaN,NaN
1,Suneratech,MNCs,Private,Hyderabad/Secunderabad Hybrid - Hyderabad/Secu...,IT Services & ConsultingPrivateForeign MNCB2B,2005 (18 yrs old),1001-5000,"We envision and build better experiences, and ...",https://img.naukimg.com/logo_images/groups/v1/...,NaN,NaN
2,HARMAN,MNCs,Private,"Hybrid - Hyderabad/Secunderabad, Pune, Chennai...",IT Services & ConsultingPrivateForeign MNCB2BA...,2001 (22 yrs old),10001-50000,"Harman Connected Services, often abbreviated t...",https://img.naukimg.com/logo_images/groups/v1/...,NaN,California
3,Nucleus Software Exports,MNCs,Public,"Hybrid - Noida Noida Noida, Chennai",Software ProductPublicIndian MNCB2BAmbitionBox...,1986 (37 yrs old),1001-5000,At Nucleus Software we provide lending and tra...,https://img.naukimg.com/logo_images/groups/v1/...,NaN,NaN
4,ION,MNCs,Private,"Mumbai Bangalore/Bengaluru Noida, Bangalore/Be...",IT Services & ConsultingHardware & NetworkingS...,1999 (24 yrs old),1001-5000,We unify your operations from front to back an...,https://img.naukimg.com/logo_images/groups/v1/...,https://jobs.lever.co/ion/6396f122-c04f-4702-8...,"New York, United States of America"

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   NAME           533 non-null    object
 1   CATEGORY       533 non-null    object
 2   INDUSTRY TYPE  533 non-null    object
 3   LOCATIONS      533 non-null    object
 4   TAGS           533 non-null    object
 5   FOUNDED        533 non-null    object
 6   SIZE           533 non-null    object
 7   ABOUT          533 non-null    object
 8   LOGO URL       533 non-null    object
 9   WEBSITE        179 non-null    object
 10  HEADQUARTERS   124 non-null    object
dtypes: object(11)
memory usage: 46.1+ KB

In [54]:
df[["NAME", "TAGS"]].head(100)

,NAME,TAGS
0,Haier Appliances,Consumer Electronics & AppliancesElectronicsMa...
1,Suneratech,IT Services & ConsultingPrivateForeign MNCB2B
2,HARMAN,IT Services & ConsultingPrivateForeign MNCB2BA...
3,Nucleus Software Exports,Software ProductPublicIndian MNCB2BAmbitionBox...
4,ION,IT Services & ConsultingHardware & NetworkingS...
...,...,...
95,Gadgeon Smart Systems,IT Services & ConsultingPrivateForeign MNCB2B
96,Cyber Infrastructure,IT Services & ConsultingPrivateForeign MNCB2B
97,Bioclinica,Pharmaceutical & Life SciencesBiotech & Life s...
98,World Resources Institute (WRI),NGO / Social Services / Industry AssociationsP...
99,Forbes Marshall,Industrial Equipment / MachineryPrivateIndian ...

In [55]:
STACK_OVERFLOW_TAGS = "./data/stackoverflow/tags.csv"

In [57]:
STACK_OVERFLOW_QUESTIONS = "./data/stackoverflow/Questions.csv"

In [58]:
STACK_OVERFLOW_ANSWERS = "./data/stackoverflow/Answers.csv"

In [59]:
so_tags = pd.read_csv(STACK_OVERFLOW_TAGS)

In [60]:
so_tags.head(10)

    Id                    Tag
0   80                   flex
1   80         actionscript-3
2   80                    air
3   90                    svn
4   90            tortoisesvn
5   90                 branch
6   90  branching-and-merging
7  120                    sql
8  120                asp.net
9  120                sitemap

In [61]:
so_tags.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3750994 entries, 0 to 3750993
Data columns (total 2 columns):
 #   Column  Dtype
---  ------  -----
 0   Id      int64
 1   Tag     object
dtypes: int64(1), object(1)
memory usage: 57.2+ MB

In [62]:
len(so_tags)

3750994

In [66]:
so_questions = pd.read_csv(STACK_OVERFLOW_QUESTIONS, encoding="ISO-8859-1", nrows=1000)

In [70]:
list(so_questions["Title"].tail(10))

['Using Yahoo! Pipes',
 'Connecting to Oracle using PHP',
 'Trip time calculation in relational databases?',
 'ORA-00161: transaction branch length 103 is illegal (maximum allowed 64',
 'What alternatives are there to the MATLAB Editor?',
 'How can I get the unique values of an array in .net?',
 'What is the difference between TrueType fonts and Type-1 fonts?',
 'How do I call a SQL Server stored procedure from PowerShell?',
 'C++ does begin/end/rbegin/rend execute in constant time for std::set, std::map, etc?',
 'Dynamically add CalendarExtender to Textbox subclass server control?']

In [71]:
so_questions

,Id,OwnerUserId,CreationDate,ClosedDate,Score,Title,Body
0,80,26.0,2008-08-01T13:57:07Z,NaN,26,SQLStatement.execute() - multiple queries in o...,<p>I've written a database generation script i...
1,90,58.0,2008-08-01T14:41:24Z,2012-12-26T03:45:49Z,144,Good branching and merging tutorials for Torto...,<p>Are there any really good tutorials explain...
2,120,83.0,2008-08-01T15:50:08Z,NaN,21,ASP.NET Site Maps,<p>Has anyone got experience creating <strong>...
3,180,2089740.0,2008-08-01T18:42:19Z,NaN,53,Function for creating color wheels,<p>This is something I've pseudo-solved many t...
4,260,91.0,2008-08-01T23:22:08Z,NaN,49,Adding scripting functionality to .NET applica...,<p>I have a little game written in C#. It uses...
...,...,...,...,...,...,...,...
995,83260,15928.0,2008-09-17T13:34:46Z,NaN,3,How can I get the unique values of an array in...,"<p>Say I've got this array:\nMyArray(0)=""aaa""\..."
996,83320,15719.0,2008-09-17T13:40:17Z,NaN,13,What is the difference between TrueType fonts ...,<p>What is the difference between TrueType fon...
997,83410,12767.0,2008-09-17T13:48:25Z,NaN,26,How do I call a SQL Server stored procedure fr...,<p>I have a large CSV file and I want to execu...
998,83640,8123.0,2008-09-17T14:09:20Z,NaN,3,C++ does begin/end/rbegin/rend execute in cons...,<p>For data types such as std::set and std::ma...
999,83770,13583.0,2008-09-17T14:24:21Z,NaN,2,Dynamically add CalendarExtender to Textbox su...,"<p>I'm trying to create a server control, whic..."

In [78]:
!ls data/stackoverflow

Answers.csv           Tags.csv
Questions.csv         question_and_tags.csv

In [79]:
STACK_OVERFLOW_QUES_WITH_TAGS = "./data/stackoverflow/question_and_tags.csv"

In [80]:
data = pd.read_csv(STACK_OVERFLOW_QUES_WITH_TAGS, encoding="ISO-8859-1", nrows=1000)

In [81]:
data

,title,tags
0,How to draw a stacked dotplot in R?,['r']
1,mysql select all records where a datetime fiel...,"['php', 'mysql']"
2,How to terminate windows phone 8.1 app,['c#']
3,get current time in a specific country via jquery,"['javascript', 'jquery']"
4,Configuring Tomcat to Use SSL,['java']
...,...,...
995,Using Python subprocess.call with crontab?,['python']
996,Updating Python for use with AWS CLI,['python']
997,Performing multiple database operations in a s...,"['ruby-on-rails', 'database', 'rest']"
998,Databinding a variable in C# to a textblock in...,"['c#', 'wpf', 'xaml']"
999,C++ OpenGL drawing a room,['c++']