In [1]:
import pandas as pd

In [34]:
data = pd.read_csv("./data/worldcities.csv")

In [18]:
data

,city,city_ascii,lat,long,country,geo2,geo3,skip1,skip2,population,id
0,Tokyo,Tokyo,35.6839,139.7744,Japan,JP,JPN,Tōkyō,primary,39105000.0,1392685764
1,Jakarta,Jakarta,-6.2146,106.8451,Indonesia,ID,IDN,Jakarta,primary,35362000.0,1360771077
2,Delhi,Delhi,28.6667,77.2167,India,IN,IND,Delhi,admin,31870000.0,1356872604
3,Manila,Manila,14.6000,120.9833,Philippines,PH,PHL,Manila,primary,23971000.0,1608618140
4,São Paulo,Sao Paulo,-23.5504,-46.6339,Brazil,BR,BRA,São Paulo,admin,22495000.0,1076532519
...,...,...,...,...,...,...,...,...,...,...,...
42900,Tukchi,Tukchi,57.3670,139.5000,Russia,RU,RUS,Khabarovskiy Kray,NaN,10.0,1643472801
42901,Numto,Numto,63.6667,71.3333,Russia,RU,RUS,Khanty-Mansiyskiy Avtonomnyy Okrug-Yugra,NaN,10.0,1643985006
42902,Nord,Nord,81.7166,-17.8000,Greenland,GL,GRL,Sermersooq,NaN,10.0,1304217709
42903,Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
42904,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468

In [22]:
# !pip install haversine
!pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.6.3-cp310-cp310-macosx_11_0_arm64.whl (7.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 781.4 kB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.7-cp310-cp310-macosx_11_0_arm64.whl (229 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.7/229.7 kB 369.3 kB/s eta 0:00:001m386.4 kB/s eta 0:00:01
Requirement already satisfied: packaging>=20.0 in ./jupyternev/lib/python3.10/site-packages (from matplotlib) (22.0)
Collecting pillow>=6.2.0
  Downloading Pillow-9.4.0-cp310-cp310-macosx_11_0_arm64.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 771.5 kB/s eta 0:00:00[36m0:00:01m eta 0:00:01
Requirement already satisfied: python-dateutil>=2.7 in ./jupyternev/lib/python3.10/site-packages (from matplotlib) (2.8.2)
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp310-cp310-macosx_11_0_arm64.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.2/63.2 kB 2.3 MB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.38.0-py3-none-any.whl (965 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 965.4/965.4 kB 766.1 kB/s eta 0:00:00 kB/s eta 0:00:01:01
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Requirement already satisfied: numpy>=1.19 in ./jupyternev/lib/python3.10/site-packages (from matplotlib) (1.24.1)
Requirement already satisfied: six>=1.5 in ./jupyternev/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.0.7 cycler-0.11.0 fonttools-4.38.0 kiwisolver-1.4.4 matplotlib-3.6.3 pillow-9.4.0 pyparsing-3.0.9

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: pip install --upgrade pip

In [10]:
import haversine as hs

In [35]:
data.columns

Index(['city', 'city_ascii', 'lat', 'long', 'country', 'geo2', 'geo3', 'skip1',
       'skip2', 'population', 'id'],
      dtype='object')

In [36]:
import matplotlib.pyplot as plt

In [42]:
data[["city", "population"]]

              city  population
0            Tokyo  39105000.0
1          Jakarta  35362000.0
2            Delhi  31870000.0
3           Manila  23971000.0
4        São Paulo  22495000.0
...            ...         ...
42900       Tukchi        10.0
42901        Numto        10.0
42902         Nord        10.0
42903  Timmiarmiut        10.0
42904      Nordvik         0.0

[42905 rows x 2 columns]

In [44]:
df = data

In [55]:
df.columns

Index(['city', 'city_ascii', 'lat', 'long', 'country', 'geo2', 'geo3', 'skip1',
       'skip2', 'population', 'id'],
      dtype='object')

In [59]:
df.query("city == city_ascii")

,city,city_ascii,lat,long,country,geo2,geo3,skip1,skip2,population,id
0,Tokyo,Tokyo,35.6839,139.7744,Japan,JP,JPN,Tōkyō,primary,39105000.0,1392685764
1,Jakarta,Jakarta,-6.2146,106.8451,Indonesia,ID,IDN,Jakarta,primary,35362000.0,1360771077
2,Delhi,Delhi,28.6667,77.2167,India,IN,IND,Delhi,admin,31870000.0,1356872604
3,Manila,Manila,14.6000,120.9833,Philippines,PH,PHL,Manila,primary,23971000.0,1608618140
5,Seoul,Seoul,37.5600,126.9900,South Korea,KR,KOR,Seoul,primary,22394000.0,1410836482
...,...,...,...,...,...,...,...,...,...,...,...
42900,Tukchi,Tukchi,57.3670,139.5000,Russia,RU,RUS,Khabarovskiy Kray,NaN,10.0,1643472801
42901,Numto,Numto,63.6667,71.3333,Russia,RU,RUS,Khanty-Mansiyskiy Avtonomnyy Okrug-Yugra,NaN,10.0,1643985006
42902,Nord,Nord,81.7166,-17.8000,Greenland,GL,GRL,Sermersooq,NaN,10.0,1304217709
42903,Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
42904,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468

In [66]:
len(data[['city_ascii', 'country']])

42905

In [67]:
len(pd.unique(data[['city_ascii', 'country']]))

ValueError: could not broadcast input array from shape (42905,2) into shape (42905,)